TP_WEB/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_WEB.Data;
using TP_WEB.Models;

namespace TP_WEB.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {
              return View(await _context.Categorias.ToListAsync());
        }

        // GET: Categorias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categorias == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categorias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Descricao,Disponivel")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categoria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categorias == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Descricao,Disponivel")] Categoria categoria)
        {
            if (id != categoria.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categorias == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categorias == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categorias'  is null.");
            }
            var categoria = await _context.Categorias.FindAsync(id);
            if (categoria != null)
            {
                _context.Categorias.Remove(categoria);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriaExists(int id)
        {
          return _context.Categorias.Any(e => e.Id == id);
        }
    }
}

TP_WEB/Controllers/VeiculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP_WEB.Data;
using TP_WEB.Models;

namespace TP_WEB.Controllers
{
    public class VeiculosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VeiculosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Veiculos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Veiculos.Include(v => v.categoria).Include(v => v.empresa);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Veiculos/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Veiculos == null)
            {
                return NotFound();
            }

            var veiculo = await _context.Veiculos
                .Include(v => v.categoria)
                .Include(v => v.empresa)
                .FirstOrDefaultAsync(m => m.Matricula == id);
            if (veiculo == null)
            {
                return NotFound();
            }

            return View(veiculo);
        }

        // GET: Veiculos/Create
        public IActionResult Create()
        {
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "Id", "Id");
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Id");
            return View();
        }

        // POST: Veiculos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Matricula,Marca,Modelo,Cor,Categoria,Nlugares,Cilindrada,Potencia,CaixaVelocidades,ArCondicionado,Combustivel,AnoDeConstrucao,Preco,CategoriaId,EmpresaId")] Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(veiculo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "Id", "Id", veiculo.CategoriaId);
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Id", veiculo.EmpresaId);
            return View(veiculo);
        }

        // GET: Veiculos/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Veiculos == null)
            {
                return NotFound();
            }

            var veiculo = await _context.Veiculos.FindAsync(id);
            if (veiculo == null)
            {
                return NotFound();
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "Id", "Id", veiculo.CategoriaId);
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Id", veiculo.EmpresaId);
            return View(veiculo);
        }

        // POST: Veiculos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Matricula,Marca,Modelo,Cor,Categoria,Nlugares,Cilindrada,Potencia,CaixaVelocidades,ArCondicionado,Combustivel,AnoDeConstrucao,Preco,CategoriaId,EmpresaId")] Veiculo veiculo)
        {
            if (id != veiculo.Matricula)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(veiculo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VeiculoExists(veiculo.Matricula))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categorias, "Id", "Id", veiculo.CategoriaId);
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Id", veiculo.EmpresaId);
            return View(veiculo);
        }

        // GET: Veiculos/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Veiculos == null)
            {
                return NotFound();
            }

            var veiculo = await _context.Veiculos
                .Include(v => v.categoria)
                .Include(v => v.empresa)
                .FirstOrDefaultAsync(m => m.Matricula == id);
            if (veiculo == null)
            {
                return NotFound();
            }

            return View(veiculo);
        }

        // POST: Veiculos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Veiculos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Veiculos'  is null.");
            }
            var veiculo = await _context.Veiculos.FindAsync(id);
            if (veiculo != null)
            {
                _context.Veiculos.Remove(veiculo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VeiculoExists(string id)
        {
          return _context.Veiculos.Any(e => e.Matricula == id);
        }
    }
}

TP_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TP_WEB</title>
    <link rel="icon" href="~/isec.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TP_WEB.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/image.css" />
    <link rel="stylesheet" href="~/css/carousel.css" asp-append-version="true" />
</head>
<body class="d-flex h-100 text-center bg-white p-0 m-0">

    <div class="cover-container d-flex w-100 h-100 p-0 mx-auto flex-column">

        <header class="p-7 text-white">

            <div class="container">

                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-grey border-bottom box-shadow fixed-top" style="background: rgba(255, 255, 255,1.0);">

                    <div class="container">

                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/img/logo.svg" alt="Logo" height="80" /></a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">INÍCIO</a>
                                </li>
                                
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Veiculos" asp-action="Index">VEICULOS</a>
                                    </li>

                                    <!--
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">CATEGORIAS</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="TipoDeAulas" asp-action="Index">AULAS</a>
                                    </li>-->
                                }
                                @if (User.Identity.IsAuthenticated)
                                {
                                    if (@User.IsInRole("Admin"))
                                    {
                                        <!--
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                Categorias
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><a class="dropdown-item" asp-controller="Categorias" asp-action="Index">Listar</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="Categorias" asp-action="Create">Criar</a></li>
                                            </ul>
                                        </li>-->
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                Veiculos
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Listar Categorias</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Criar Categoria</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Editar Categoria</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Apagar Categoria</a></li>
                                            </ul>
                                        </li>
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                Empresas
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Listar Empresas</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Gerir Empresas</a></li> <!--Ativar/Desativar empresas-->
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Adicionar Empresas</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Editar Empresas</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Apagar Empresas</a></li>
                                            </ul>
                                        </li>
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                Utilizadores
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Listar Utilizadores</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="#" asp-action="#">Editar Utilizadores</a></li> <!--Ativar/Desativar utilizadores-->
                                                <!--
                                                <li><a class="dropdown-item" asp-controller="GestaoUsers" asp-action="Index">Users</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="RoleManager" asp-action="Index">Gestão de Roles</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="UserRolesManager" asp-action="Index">Associar Roles</a></li>
                                                <li><a class="dropdown-item" asp-controller="Agendamentos" asp-action="Index">Agendamentos</a></li>
                                                -->
                                            </ul>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="#" asp-action="#">DashBoard</a>
                                        </li>
                                    }
                                    else if (@User.IsInRole("Cliente"))
                                    {
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                AGENDAMENTOS
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="Agendamentos" asp-action="OsMeusAgendamentos">Os meus agendamentos</a></li>
                                                <li><hr class="dropdown-divider"></li>
                                                <li><a class="dropdown-item" asp-controller="Agendamentos" asp-action="Pedido">Pedido de Agendamento</a></li>
                                            </ul>
                                        </li>
                                    }
                                }
                                <li></li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contactos">CONTACTOS</a>
                                </li>
                            </ul>
                            <!--<partial name="~/Views/Cursos/QuickSearchPartial.cshtml" />-->
                            <partial name="_LoginPartial" />

                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <main class="container mt-5 pt-5 text-start">
            @RenderBody()
        </main>

        <footer class="border-top footer text-muted">
            <div class="container">
                <br />&copy Nuno & Patricia 2022 - PWEB Aulas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/method_pt.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>